name: FastAPI Testing

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: chapter5/requirements-dev.lock

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements-dev.lock
        working-directory: chapter5

      - name: Run Tests
        run: pytest
        working-directory: chapter5
